### ISSUE TITLE
Error creating source-target field

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#101]
Start Time: Thursday, January 26, 2017 2:26:09 PM
Running script SourceTargetMapping...
Source: C:\_MyFiles\GitHub\utility-data-models\Utility Network Data Migration\Water to UN\WaterUtilities.gdb\WaterDistribution\wCurbStopValve
Target: C:\Users\mich3661\Documents\ArcGIS\Projects\MyProject8\WaterUser@water.sde\Water.WATERUSER.Water\Water.WATERUSER.WaterDevice
File: C:\_MyFiles\GitHub\utility-data-models\Utility Network Data Migration\Water_to_UN\CurbStopValves.xml
Failed script SourceTargetMapping...
Traceback (most recent call last):
  File "C:\Users\mich3661\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaCreateSourceTarget.py", line 323, in <module>
    main()
  File "C:\Users\mich3661\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaCreateSourceTarget.py", line 64, in main
    createDlaFile(source,target,xmlFileName)
  File "C:\Users\mich3661\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaCreateSourceTarget.py", line 76, in createDlaFile
    writeDocument(sourcePath,targetPath,xmlFileName)
  File "C:\Users\mich3661\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaCreateSourceTarget.py", line 138, in writeDocument
    xmlDoc.writexml( open(xmlFileName, 'wt', encoding='utf-8'),indent="  ",addindent="  ",newl='\n')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\_MyFiles\\GitHub\\utility-data-models\\Utility Network Data Migration\\Water_to_UN\\CurbStopValves.xml'
Failed to execute (SourceTargetMapping).
Failed at Thursday, January 26, 2017 2:26:11 PM (Elapsed Time: 1.83 seconds)

**Comment by MikeMillerGIS** [comment]
It ran when I did it again with a different file name.  So I wonder if I did something bad to the path.
this works
C:\_MyFiles\GitHub\utility-data-models\Utility Network Data Migration\Water to UN\CurbStopValves.xml

this did not.  Not sure where I got the wonky path.  
C:\_MyFiles\GitHub\utility-data-models\Utility Network Data Migration\Water_to_UN\CurbStopValves.xml
