### ISSUE TITLE
Error in stage when running tool in pro

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#119]
Traceback (most recent call last):  File "C:\Users\mich3661\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaStage.py", line 92, in <module>    main()  File "C:\Users\mich3661\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaStage.py", line 31, in main    stage(xmlFileNames)  File "C:\Users\mich3661\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaStage.py", line 81, in stage    xmlDoc.writexml( open(xmlFileName, 'wt', encoding='utf-8'))OSError: [Errno 22] Invalid argument: "'C:\\_MyFiles\\GitHub\\utility-data-models\\Data Migration\\WaterAssetPackage\\ControlValves.xml'"

cause is the extra ' in the path

**Comment by MikeMillerGIS** [comment]
Installed, please verify

**Comment by previnWong** [comment]
verified.
