### ISSUE TITLE
Error if you do not establish an initial connection

### ISSUE THREAD

**Issue by previnWong** [Esri/data-assistant#126]
If you open the Pro project and it contains data in an enterprise geodatabase, you need to establish a connection via the sde connection before you can create an DA config file.

If you open the pro project and try to make a config file right away, you get the following error:
```
Running script SourceTargetMapping...
Source: Transformer
Target: Electric Device
File: C:\Users\Win10\Downloads\UN_SampleData\DataAssistantFIles_EGDB\test.xml
Used data source property
Transformer
Used data source property
Electric Device
Failed script SourceTargetMapping...
Traceback (most recent call last):  File "C:\Users\Win10\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaCreateSourceTarget.py", line 331, in <module>    main()  File "C:\Users\Win10\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaCreateSourceTarget.py", line 72, in main    createDlaFile(source,target,xmlFileName)  File "C:\Users\Win10\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaCreateSourceTarget.py", line 83, in createDlaFile    targetPath = dla.getLayerPath(target)  File "C:\Users\Win10\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dla.py", line 798, in getLayerPath    pth = repairLayerSourceUrl(pth,layer)  File "C:\Users\Win10\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dla.py", line 870, in repairLayerSourceUrl    connfile = getConnectionFile(lyr.connectionProperties)  File "C:\Users\Win10\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dla.py", line 1001, in getConnectionFile    date=getcp(cp,'date'))  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 17073, in CreateDatabaseConnection    raise e  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 17070, in CreateDatabaseConnection    retval = convertArcObjectToPythonObject(gp.CreateDatabaseConnection_management(*gp_fixargs((out_folder_path, out_name, database_platform, instance, account_authentication, username, password, save_user_pass, database, schema, version_type, version, date), True)))  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\geoprocessing\_base.py", line 506, in <lambda>    return lambda *args: val(*gp_fixargs(args, True))arcgisscripting.ExecuteError:  ERROR 999999: Error executing function.Failed to execute (CreateDatabaseConnection).
Failed to execute (SourceTargetMapping).
```

**Comment by SteveGrise** [comment]
I don't understand what 'you need to establish a connection via the sde connection' means. I'm having a hard time reading through these issues to figure out what the actual issue is and how to reproduce it.

**Comment by previnWong** [comment]
If you are making a new data assistant config file.  If one of your target or source is an connection to an enterprise database through an SDE connection, you have to make sure you double click the connection to establish a connection to the enterprise DB before you run the command to create a data assistance config file otherwise you get the error pasted above.

**Comment by SteveGrise** [comment]
I do not experience that problem. This is related to a question that I asked for some help on - auto-creating .sde files and/or using the CIM Workspace properties through python. The result I currently experience is:
![image](https://cloud.githubusercontent.com/assets/4749060/23760447/b7c6bbca-04bd-11e7-9f6f-cc49c06222cf.png)

**Comment by previnWong** [comment]
No longer seeing this issue. Verified.

**Comment by previnWong** [comment]
Behavior occurred again. open Pro project with data coming from a enterprise database (layers unchecked).  Create a new config file command.  Choose an enterprise gdb layer as a target from the drop down list.  press Run. get the following error.
![image](https://cloud.githubusercontent.com/assets/11183838/24020250/8f673c4a-0a58-11e7-87b8-ad449e3da1ab.png)

Now, go to the project panel, Databases node and double click the sde connection to make a connection. Next, run make a new config again. This time to creates it fine.
![image](https://cloud.githubusercontent.com/assets/11183838/24020306/d21eddea-0a58-11e7-840f-8c80e6a2891b.png)

**Comment by SteveGrise** [comment]
Since this is intermittent I suggest we call this a known issue and see if there are any product bugs or plans to address this in the core software. I don't think there is anything I can do in DA to address this.

**Comment by previnWong** [comment]
Documenting it as a known behavior. limitation of Pro.

**Comment by MikeMillerGIS** [comment]
I can repo pretty easily.  @previnWong can you create a very simple python script as a repo case we can send Dev.  Looks like Steve is just get the connection properties from the layer, dissecting them, and calling createEnterpriseGDBConnection.

**Comment by MikeMillerGIS** [comment]
Can we change getCP to default to None?  maybe exclude Date also?

**Comment by SteveGrise** [comment]
I'm going to drop items from the argument list if they do not exist in the
connection properties.

**Comment by previnWong** [comment]
Adding note to establish a connection first before running tools to the wiki.
https://github.com/Esri/data-assistant/wiki/Ensure-Database-Connections-Before-Running-Tools
