### ISSUE TITLE
Do not check source feature service for edit capabilites - only check target feature service

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/data-assistant#157]
Start Time: Friday, April 14, 2017 10:25:44 AM
Running script SourceTargetMapping...
Source: KansasCityParcels
Target: Parcels
File: C:\Users\chri4819\Documents\ArcGIS\Projects\MyProject17\ServicetoService.xml
Used data source property
KansasCityParcels
Used data source property
Parcels
Service Name: KansasCityParcels
Service REST capabilities: "Query"
Service does not support: Create
Service does not support: Delete
Failed script SourceTargetMapping...
Traceback (most recent call last):
  File "C:\Users\chri4819\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaCreateSourceTarget.py", line 334, in <module>
    main()
  File "C:\Users\chri4819\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaCreateSourceTarget.py", line 72, in main
    createDlaFile(source,target,xmlFileName)
  File "C:\Users\chri4819\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaCreateSourceTarget.py", line 84, in createDlaFile
    writeDocument(sourcePath,targetPath,xmlFileName)
  File "C:\Users\chri4819\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaCreateSourceTarget.py", line 95, in writeDocument
    if not dlaService.checkServiceCapabilities(sourcePath,False):
  File "C:\Users\chri4819\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaService.py", line 354, in checkServiceCapabilities
    dla.addWarning('WARNING: ' + name + ' does not have Create and Delete privileges')
AttributeError: module 'dla' has no attribute 'addWarning'
Failed to execute (SourceTargetMapping).
Failed at Friday, April 14, 2017 10:25:45 AM (Elapsed Time: 1.29 seconds)

**Comment by ChrisBuscaglia** [comment]
Fixed
