### ISSUE TITLE
Unable to create config file with 4-21-17 build

### ISSUE THREAD

**Issue by previnWong** [Esri/data-assistant#161]
@SteveGrise Not doing anything cute, just the same step and same map I have been using the last week.  With Today's build, cannot create a config file.  Select source from drop down, select target from drop down, try to save file, error below.  Using the sde connections with the .sde in the name.

Start Time: Friday, April 21, 2017 9:05:46 AM
Running script SourceTargetMapping...
Source: source_db_925.sde.ElectricDistributionAssembly
Target: target_db_930.sde.ElectricDistributionAssembly
File: C:\Users\Win10\Downloads\DA_test\test88t.xml
Used data source property
source_db_925.sde.ElectricDistributionAssembly
Used data source property
target_db_930.sde.ElectricDistributionAssembly
Failed script SourceTargetMapping...
Traceback (most recent call last):
  File "C:\Users\Win10\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaCreateSourceTarget.py", line 343, in <module>
    main()
  File "C:\Users\Win10\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaCreateSourceTarget.py", line 72, in main
    createDlaFile(source,target,xmlFileName)
  File "C:\Users\Win10\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaCreateSourceTarget.py", line 83, in createDlaFile
    targetPath = dla.getLayerPath(target)
  File "C:\Users\Win10\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dla.py", line 868, in getLayerPath
    pth = repairLayerSourceUrl(pth,layer)
  File "C:\Users\Win10\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dla.py", line 940, in repairLayerSourceUrl
    connfile = getConnectionFile(lyr.connectionProperties)
  File "C:\Users\Win10\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dla.py", line 1052, in getConnectionFile
    dir = os.path.dirname(_xmlFolder) # change to xmlfolder since this will be better for portability when xml/data outside of the project
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\ntpath.py", line 239, in dirname
    return split(p)[0]
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\ntpath.py", line 204, in split
    d, p = splitdrive(p)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\ntpath.py", line 139, in splitdrive
    if len(p) >= 2:
TypeError: object of type 'NoneType' has no len()
Failed to execute (SourceTargetMapping).
Failed at Friday, April 21, 2017 9:05:48 AM (Elapsed Time: 1.77 seconds)

![image](https://cloud.githubusercontent.com/assets/11183838/25286309/22f02546-2672-11e7-92a3-d8da5ca74840.png)

**Comment by SteveGrise** [comment]
@previnWong I posted an update, while this should resolve the current issue the next lines of code it will hit will be the untested connection file creation code for postgres.

**Comment by previnWong** [comment]
verified
