### ISSUE TITLE
Test DA Workspace - a predefined workspace for the Data Assistant

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/data-assistant#247]
- 
-     All feature class inputs and output
-     When input is already a layer
-     Feature Service as inputs and output
-     Non editable services as output
-

**Comment by ChrisBuscaglia** [comment]
Failed - 

ImageTraceback (most recent call last):  File "C:\Users\chri4819\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\pyt\DATools.py", line 45, in execute    arcpy.SetParameter(len(params)-1, results)  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\__init__.py", line 687, in SetParameter    return gp.setParameter(index, value)  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\geoprocessing\_base.py", line 248, in setParameter    self._gp.SetParameter(*gp_fixargs(args, True)))RuntimeError: Object: Error in setting parameter
ImageFailed to execute (Append).
